# Generated by Django 4.2.4 on 2024-02-22 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventspage_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspage',
            name='event_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 22), null=True),
        ),
    ]
