# Generated by Django 4.2.4 on 2024-02-27 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventspage_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='event_img_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='event_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 27), null=True),
        ),
    ]
