# Generated by Django 4.2.4 on 2024-02-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventspage_event_img_url_alter_eventspage_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='event_tags',
            field=models.TextField(blank=True),
        ),
    ]
