# Generated by Django 4.2.4 on 2024-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventspage_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='event_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
