# Generated by Django 4.2.4 on 2024-03-18 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventspage_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspage',
            name='event_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 18), null=True),
        ),
    ]
