# Generated by Django 5.0.1 on 2024-01-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='project_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
