# Generated by Django 4.2.4 on 2024-02-22 12:52

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectspage_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspage',
            name='project_description',
            field=wagtailmarkdown.fields.MarkdownField(null=True),
        ),
    ]
