# Generated by Django 4.2.4 on 2024-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectspage_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='project_img_url',
            field=models.URLField(null=True),
        ),
    ]
