# Generated by Django 4.2.4 on 2024-02-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectspage_project_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='project_tags',
            field=models.TextField(blank=True),
        ),
    ]
