# Generated by Django 4.2.4 on 2024-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectspage_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='project_authors',
            field=models.TextField(blank=True),
        ),
    ]
