# Generated by Django 4.2.4 on 2024-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectspage_project_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='project_year',
            field=models.TextField(blank=True),
        ),
    ]
