# Generated by Django 4.2.4 on 2024-03-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectspage_project_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspage',
            name='project_year',
            field=models.IntegerField(blank=True),
        ),
    ]
