# Generated by Django 4.2.4 on 2024-02-22 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='published_on',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 22), null=True),
        ),
    ]
