# Generated by Django 4.2.4 on 2024-02-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_authors',
            field=models.TextField(blank=True),
        ),
    ]
