# Generated by Django 4.2.4 on 2024-02-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpage_blog_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_img_url',
            field=models.URLField(null=True),
        ),
    ]
