# Generated by Django 4.2.4 on 2024-02-27 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_blog_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='published_on',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 27), null=True),
        ),
    ]
