# Generated by Django 4.2.4 on 2024-02-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpage_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_tags',
            field=models.TextField(blank=True),
        ),
    ]
