# Generated by Django 5.0.1 on 2024-01-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberspage',
            name='members_slug',
            field=models.IntegerField(null=True),
        ),
    ]
